version: '3'

tasks:
  _build:
    cmds:
      - docker buildx build .
        --file ./Dockerfile
        --network=host
        --build-arg="GCC_VERSION={{.version}}"
        --tag curoky/devspace:prebuilt-gcc-{{.version}}
  11.5.0:
    deps:
      - task: _build
        vars:
          version: 11.5.0
  12.4.0:
    deps:
      - task: _build
        vars:
          version: 12.4.0
  13.4.0:
    deps:
      - task: _build
        vars:
          version: 13.4.0
  14.2.0:
    deps:
      - task: _build
        vars:
          version: 14.2.0
  14.3.0:
    deps:
      - task: _build
        vars:
          version: 14.3.0
  15.1.0:
    deps:
      - task: _build
        vars:
          version: 15.1.0
  all:
    - task: 11.5.0
    - task: 12.4.0
    - task: 13.4.0
    # - task: 14.2.0
    - task: 14.3.0
    - task: 15.1.0
    - docker push curoky/devspace:prebuilt-gcc-11.5.0
    - docker push curoky/devspace:prebuilt-gcc-12.4.0
    - docker push curoky/devspace:prebuilt-gcc-13.4.0
    - docker push curoky/devspace:prebuilt-gcc-14.3.0
    - docker push curoky/devspace:prebuilt-gcc-15.1.0
