version: '3'

tasks:
  _build:
    cmds:
      - docker build .
        --file ./Dockerfile
        --network=host
        --build-arg="GCC_VERSION={{.version}}"
        --tag curoky/devspace:deps-gcc-{{.version}}
  11.5.0:
    deps:
      - task: _build
        vars:
          version: 11.5.0
  12.4.0:
    deps:
      - task: _build
        vars:
          version: 12.4.0
  13.4.0:
    deps:
      - task: _build
        vars:
          version: 13.4.0
  14.3.0:
    deps:
      - task: _build
        vars:
          version: 14.3.0
  15.2.0:
    deps:
      - task: _build
        vars:
          version: 15.2.0
  all_parallel:
    deps:
      - 11.5.0
      - 12.4.0
      - 13.4.0
      - 14.3.0
      - 15.2.0
  all:
    - task: 11.5.0
    - task: 12.4.0
    - task: 13.4.0
    - task: 14.3.0
    - task: 15.2.0
  push:
    - docker push curoky/devspace:deps-gcc-11.5.0
    - docker push curoky/devspace:deps-gcc-12.4.0
    - docker push curoky/devspace:deps-gcc-13.4.0
    - docker push curoky/devspace:deps-gcc-14.3.0
    - docker push curoky/devspace:deps-gcc-15.2.0
