version: '3'

tasks:
  _build:
    cmds:
      - docker build .
        --file Dockerfile
        --network=host
        --build-arg="LLVM_VERSION={{.version}}"
        --tag curoky/devspace:deps-llvm-{{.version}}
  16.0.6:
    deps:
      - task: _build
        vars:
          version: 16.0.6
  17.0.6:
    deps:
      - task: _build
        vars:
          version: 17.0.6
  18.1.8:
    deps:
      - task: _build
        vars:
          version: 18.1.8
  19.1.7:
    deps:
      - task: _build
        vars:
          version: 19.1.7
  20.1.8:
    deps:
      - task: _build
        vars:
          version: 20.1.8
  21.1.0:
    deps:
      - task: _build
        vars:
          version: 21.1.0

  all_parallel:
    deps:
      - 21.1.0
      - 20.1.8
      - 19.1.7
      - 18.1.8
      - 17.0.6
      - 16.0.6
  all:
    - task: 21.1.0
    - task: 20.1.8
    - task: 19.1.7
    - task: 18.1.8
    - task: 17.0.6
    - task: 16.0.6
  push:
    - docker push curoky/devspace:deps-llvm-16.0.6
    - docker push curoky/devspace:deps-llvm-17.0.6
    - docker push curoky/devspace:deps-llvm-18.1.8
    - docker push curoky/devspace:deps-llvm-19.1.7
    - docker push curoky/devspace:deps-llvm-20.1.8
    - docker push curoky/devspace:deps-llvm-21.1.0
