default_stages: [commit]
repos:
  # >>>>>>>>>>>>>>>>>>>>> basic <<<<<<<<<<<<<<<<<<<< #
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.5.0'
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      # - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      # - id: double-quote-string-fixer
      - id: end-of-file-fixer
      # - id: requirements-txt-fixer
      - id: trailing-whitespace
      - id: sort-simple-yaml
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v4.0.0-alpha.8'
    hooks:
      - id: prettier
  - repo: https://github.com/commitizen-tools/commitizen
    rev: 'v3.13.0'
    hooks:
      - id: commitizen
        stages: [commit-msg]
  # >>>>>>>>>>>>>>>>>>>>> basic <<<<<<<<<<<<<<<<<<<< #

  # >>>>>>>>>>>>>>>>>>>>> bash <<<<<<<<<<<<<<<<<<<< #
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: 'v3.7.0-4'
    hooks:
      - id: shfmt
        args: ['-w', '-i', '2', '-s', '-l', '-ci']
  # >>>>>>>>>>>>>>>>>>>>> bash <<<<<<<<<<<<<<<<<<<< #

  # >>>>>>>>>>>>>>>>>>>>> python <<<<<<<<<<<<<<<<<<<< #
  - repo: https://github.com/psf/black
    rev: '23.12.1'
    hooks:
      - id: black
      - id: black-jupyter
  - repo: https://github.com/nbQA-dev/nbQA
    rev: '1.7.1'
    hooks:
      - id: nbqa-black
      - id: nbqa-ruff
        args: [--fix]
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.1.13'
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --no-cache]
  # >>>>>>>>>>>>>>>>>>>>> python <<<<<<<<<<<<<<<<<<<< #

  # >>>>>>>>>>>>>>>>>>>>> c++ <<<<<<<<<<<<<<<<<<<< #
  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: 'v0.6.13'
    hooks:
      - id: cmake-format
  - repo: https://github.com/cpplint/cpplint
    rev: '1.6.1'
    hooks:
      - id: cpplint
        args: ['--linelength=100']
  - repo: https://github.com/keith/pre-commit-buildifier
    rev: '6.4.0'
    hooks:
      - id: buildifier
  # - repo: https://github.com/cheshirekow/cmake-format-precommit
  #   rev: 'v0.6.13'
  #   hooks:
  #     - id: cmake-format
  # >>>>>>>>>>>>>>>>>>>>> c++ <<<<<<<<<<<<<<<<<<<< #

  # >>>>>>>>>>>>>>>>>>>>> ruby <<<<<<<<<<<<<<<<<<<< #
  # - repo: https://github.com/rubocop/rubocop
  #   rev: 'v1.52.0'
  #   hooks:
  #     - id: rubocop
  # >>>>>>>>>>>>>>>>>>>>> ruby <<<<<<<<<<<<<<<<<<<< #

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: 'v17.0.6'
    hooks:
      - id: clang-format
        'types_or': [c++, c, c#, cuda, java, objective-c, proto]
