default_stages: [commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.1.0'
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: double-quote-string-fixer
      - id: end-of-file-fixer
      # - id: pretty-format-json
      #   args: ['--autofix']
      # - id: requirements-txt-fixer
      - id: trailing-whitespace
  - repo: https://github.com/commitizen-tools/commitizen
    rev: 'v2.20.3'
    hooks:
      - id: commitizen
        stages: [commit-msg]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v2.5.1'
    hooks:
      - id: prettier
  - repo: https://github.com/pre-commit/mirrors-yapf
    rev: 'v0.32.0'
    hooks:
      - id: yapf
  - repo: https://github.com/asottile/pyupgrade
    rev: 'v2.31.0'
    hooks:
      - id: pyupgrade
  - repo: https://github.com/yoheimuta/protolint
    rev: 'v0.35.2'
    hooks:
      - id: protolint
  # - repo: https://github.com/markdownlint/markdownlint
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: 'v0.30.0'
    hooks:
      - id: markdownlint
  - repo: https://github.com/rubocop/rubocop
    rev: 'v1.24.1'
    hooks:
      - id: rubocop
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: 'v0.8.0.3'
    hooks:
      - id: shellcheck
  - repo: https://github.com/cpplint/cpplint
    rev: '1.5.5'
    hooks:
      - id: cpplint
        args: ['--linelength=100']
  # - repo: https://github.com/cheshirekow/cmake-format-precommit
  #   rev: 'v0.6.13'
  #   hooks:
  #     - id: cmake-format
  #     - id: cmake-lint
  # - repo: https://github.com/PyCQA/pylint
  #   rev: 'v2.12.2'
  #   hooks:
  #     - id: pylint
  - repo: https://github.com/PyCQA/isort
    rev: '5.10.1'
    hooks:
      - id: isort
  - repo: https://github.com/golangci/golangci-lint
    rev: 'v1.43.0'
    hooks:
      - id: golangci-lint
  # - repo: https://github.com/adrienverge/yamllint
  #   rev: 'v1.26.3'
  #   hooks:
  #     - id: yamllint
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: 'v13.0.0'
    hooks:
      - id: clang-format
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: 'v3.4.2-1'
    hooks:
      - id: shfmt
        args: ['-w', '-i', '2', '-s', '-l', '-ci']
  # - repo: https://github.com/pocc/pre-commit-hooks
  #   rev: v1.3.5
  #   hooks:
  #     - id: cppcheck
  - repo: https://github.com/keith/pre-commit-buildifier
    rev: '4.2.3'
    hooks:
      - id: buildifier
      - id: buildifier-lint
  - repo: https://github.com/curoky/licenseheaders
    rev: 'v0.9.0'
    hooks:
      - id: licenseheaders
        args:
          - '--tmpl=apache-2'
          - '--owner=curoky(cccuroky@gmail.com)'
          - '--years=2020'
          - '--exclude'
          - 'README.md'
          - '*.md'
          - '*.rb'
          - '*.yaml'
          - '*.yml'
          - '*.xml'
          - '*Dockerfile'
          - '--files'
