actions:
  fix-sshd-host-key-permissions: chmod 600 /etc/ssh/ssh_host*
  fix-ssh_config-permissions: chmod 600 config/ssh/ssh_config
config:
  banner: false
  dotpath: config
  link_dotfile_default: link
  link_on_import: link
  template_dotfile_default: false
  minversion: 1.14.0
dotfiles:
  apt-proxy:
    dst: /etc/apt/apt.conf.d/proxy
    link: nolink
    src: apt/apt.conf.d/proxy
  apt-ubuntu-mirror-cn:
    dst: /etc/apt/sources.list
    link: nolink
    src: apt/sources-ubuntu-mirror-cn.list
  bash_logout:
    dst: ~/.bash_logout
    src: bash/bash_logout
  bashrc:
    dst: ~/.bashrc
    src: bash/bashrc
  bat:
    dst: ~/.config/bat
    src: bat
  bazel:
    dst: ~/.bazelrc
    src: bazel/bazelrc
  cargo:
    dst: ~/.cargo/config.toml
    src: cargo/config.toml
  ccache:
    dst: ~/.config/ccache/ccache.conf
    src: ccache/ccache.conf
  clang-format:
    dst: ~/.clang-format
    src: clang-format/clang-format
  cmake-format:
    dst: ~/.cmake-format.json
    src: cmake-format/cmake-format.json
  conan:
    dst: ~/.conan/conan.conf
    src: conan/conan.conf
  conda:
    dst: ~/.config/conda/condarc
    src: conda/condarc
  crontab:
    dst: /etc/cron.d/custom.crontab
    link: nolink
    src: crontab/custom.crontab
  dircolors:
    dst: ~/.dircolors
    src: ls/dircolors
  docker:
    dst: ~/.docker/config.json
    src: docker/config.json
  docker-d:
    dst: /etc/docker/daemon.json
    link: nolink
    src: docker/daemon.json
  docker-proxy:
    dst: /etc/systemd/system/docker.service.d/http-proxy.conf
    link: nolink
    src: docker/http-proxy.conf
  dolthub:
    dst: ~/.dolt
    src: dolthub
  gdb:
    dst: ~/.gdbinit
    src: gdb/gdbinit
  git-config:
    dst: ~/.gitconfig
    src: git/.gitconfig
  git-key:
    dst: ~/dotbox/config/ssh/id_rsa-github.origin
    src: ssh/id_rsa-github
    link: nolink
    chmod: '600'
    trans_install: _decrypt
    trans_update: _encrypt
  go:
    dst: ~/.config/go
    src: go
  golangci:
    dst: ~/.golangci.yaml
    src: golangci/golangci.yaml
  goproxy-systemd:
    dst: /lib/systemd/system/goproxy.service
    link: nolink
    src: goproxy/goproxy.service
  gost-d:
    dst: /etc/gost/daemon.json
    link: nolink
    src: gost/daemon.json
  gost-systemd:
    dst: /lib/systemd/system/gost.service
    link: nolink
    src: gost/gost.service
  gradle:
    dst: ~/.gradle/gradle.properties
    src: gradle/gradle.properties
  helix:
    dst: ~/.config/helix
    src: helix
  htop:
    dst: ~/.config/htop/htoprc
    src: htop/htoprc
  httpbin:
    dst: /lib/systemd/system/go-httpbin.service
    link: nolink
    src: httpbin/go-httpbin.service
  hyper:
    dst: ~/.hyper.js
    src: hyper/hyper.js
  isort:
    dst: ~/.isort.cfg
    src: isort/isort.cfg
  jupyter:
    dst: ~/.jupyter
    src: jupyter
  linux-environment:
    dst: /etc/environment
    link: nolink
    src: linux/environment
  linux-journal:
    dst: /etc/systemd/journald.conf
    link: nolink
    src: systemd/journald.conf
  linux-profile-homebrew-mirror-cn:
    dst: /etc/profile.d/homebrew-mirror-cn.sh
    link: nolink
    src: linux/profile.d/homebrew-mirror-cn.sh
  linux-sudoers_more_secure_path:
    dst: /etc/sudoers.d/more_secure_path
    link: nolink
    src: linux/sudoers.d/more_secure_path
  linux-sudoers_nopasswd_user:
    dst: /etc/sudoers.d/nopasswd_user
    link: nolink
    src: linux/sudoers.d/nopasswd_user
  linux-sysctl:
    dst: /etc/sysctl.d/custom.conf
    link: nolink
    src: linux/sysctl.d/custom.conf
  markdownlint:
    dst: ~/.markdownlintrc
    src: markdownlint/markdownlintrc
  maven:
    dst: ~/.m2/settings.xml
    src: maven/settings.xml
  navi:
    dst: ~/.config/navi
    src: navi
  navi-cheats:
    dst: ~/.local/share/navi/cheats/local
    src: navi-cheats
  neofetch:
    dst: ~/.config/neofetch
    src: neofetch
  nix:
    dst: /etc/nix/nix.conf
    link: nolink
    src: nixpkgs/nix.conf
  nix-mirror-cn:
    dst: /etc/nix/nix.conf
    link: nolink
    src: nixpkgs/nix-mirror-cn.conf
  nixpkgs:
    dst: ~/.config/nixpkgs/config.nix
    src: nixpkgs/config.nix
  pip:
    dst: ~/.config/pip
    src: pip
  prettier:
    dst: ~/.prettierrc.yaml
    src: prettier/prettierrc.yaml
  procps:
    dst: ~/.config/procps
    src: procps
  profile:
    dst: ~/.profile
    src: bash/profile
  pylintrc:
    dst: ~/.config/pylintrc
    src: pylint/pylintrc
  rime:
    dst: ~/Library/Rime
    src: rime/squirrel
  rubocop:
    dst: ~/.rubocop.yml
    src: rubocop/rubocop.yml
  shellcheck:
    dst: ~/.shellcheckrc
    src: shellcheck/shellcheckrc
  snipaste:
    dst: ~/.snipaste/config.ini
    src: snipaste/config.ini
  ssh-authorized-key:
    dst: ~/.ssh/authorized_keys
    src: ssh/authorized_keys
  ssh-d:
    dst: /etc/ssh/sshd_config.d/custom.conf
    link: nolink
    src: ssh/sshd-custom.conf
  ssh-systemd-socket:
    dst: /etc/systemd/system/ssh.socket.d/custom.conf
    link: nolink
    src: ssh/systemd-ssh-socket.conf
  ssh-host-key:
    actions:
      - fix-sshd-host-key-permissions
    dst: /etc/ssh
    link: nolink
    src: ssh/host-key
  ssh-config:
    dst: ~/.ssh/config
    actions:
      - fix-ssh_config-permissions
    src: ssh/ssh_config
  startship:
    dst: ~/.config/starship.toml
    src: starship/starship.toml
  tabby:
    dst: ~/Library/Application Support/tabby
    src: tabby
  terminalizer:
    dst: ~/.terminalizer
    src: terminalizer
  tmux:
    dst: ~/.tmux.conf
    src: tmux/tmux.conf
  tmux-local:
    dst: ~/.tmux.conf.local
    src: tmux/tmux.conf.local
  vim:
    dst: ~/.vimrc
    src: vim/vimrc
  vscode-snippets:
    dst: ~/Library/Application Support/Code/User/snippets
    src: vscode/app/snippets
  vscode-keybindings:
    dst: ~/Library/Application Support/Code/User/keybindings.json
    src: vscode/app/keybindings.json
  vscode-settings:
    dst: ~/Library/Application Support/Code/User/settings.json
    src: vscode/app/settings.json
  vscode-server:
    dst: ~/.vscode-server/data/Machine/settings.json
    src: vscode/remote-server-settings.json
  warp:
    dst: ~/.warp
    src: warp
  yapf:
    dst: ~/.style.yapf
    src: yapf/style.yapf
  yarn:
    dst: ~/.yarnrc
    src: yarn/yarnrc
  zshenv-etc:
    dst: /etc/zshenv
    link: nolink
    src: zsh/etc/zshenv
  zshenv-etc-homebrew-mirror-cn:
    dst: /etc/zshenv.d/homebrew-mirror-cn.zsh
    link: nolink
    src: zsh/etc/zshenv.d/homebrew-mirror-cn.zsh
  zshenv-etc-golang-proxy-cn:
    dst: /etc/zshenv.d/golang-proxy-cn.zsh
    link: nolink
    src: zsh/etc/zshenv.d/golang-proxy-cn.zsh
  zshrc:
    dst: ~/.zshrc
    src: zsh/zshrc
profiles:
  devbox-sysconf:
    dotfiles:
      - docker-d
      - linux-journal
      - linux-sudoers_more_secure_path
      - linux-sysctl
      - ssh-d
      - ssh-systemd-socket
      - ssh-host-key
      - zshenv-etc

  devbox-sysconf-proxy:
    dotfiles:
      - apt-proxy
      - docker-proxy

  devbox-sysconf-mirror-cn:
    dotfiles:
      - apt-ubuntu-mirror-cn
      - nix-mirror-cn
      - linux-profile-homebrew-mirror-cn
      - zshenv-etc-homebrew-mirror-cn
      - zshenv-etc-golang-proxy-cn

  devbox-userconf-base:
    dotfiles:
      - bash_logout
      - bashrc
      - bat
      - cargo
      - ccache
      - clang-format
      - conda
      - dolthub
      - gdb
      - gradle
      - htop
      - isort
      - nixpkgs
      - pip
      - prettier
      - procps
      - profile
      - ssh-authorized-key
      - startship
      - tmux
      - vim
      - vscode-server
      - yapf

  devbox-userconf-outofbox:
    include:
      - devbox-userconf-base
    dotfiles:
      - docker
      - git-config
      - ssh-config
      - maven
      - zshrc

  macos-userconf:
    dotfiles:
      - bat
        # - cargo
        # - clang-format
        # - conda
      - git-config
        # - gradle
        # - isort
        # - maven
      - pip
      - prettier
      - procps
      - profile
      - rime
      - snipaste
      - ssh-authorized-key
      - ssh-config
      - startship
      - vim
      - vscode-keybindings
      - vscode-settings
      - vscode-snippets
        # - yapf
      - zshrc
trans_install:
  _decrypt:
    openssl enc -aes-256-cbc -nosalt -d -pbkdf2 -in {0} -out {1} -pass pass:{{@@
    env['SECRET'] @@}}
trans_update:
  _encrypt:
    openssl enc -aes-256-cbc -nosalt -pbkdf2 -in {0} -out {1} -pass pass:{{@@
    env['SECRET'] @@}}
