default_image: ghcr.io/curoky/devspace:codespace-debian13

container:
  cap_add: [NET_RAW, SYS_ADMIN]
  security_opt: [disable, seccomp=unconfined]
  pids_limit: -1
  ulimits:
    - {name: memlock, soft: -1, hard: -1}
  mounts:
    - {source: /etc/krb5.conf, target: /etc/krb5.conf, read_only: true}

hosts:
  local:
    type: podman-machine
    machine: podman-machine-default
    network_mode: host

tokens:
  github:
  gitlab:

projects:
  devspace:
    repo: github:curoky/devspace
    host:
      - name: local
        platform: linux/arm64

  standalone-binaries:
    repo: github:curoky/standalone-binaries
    host:
      - name: local
        platform: linux/arm64

  devspace2:
    repo: git:git@curoky:devspace
    host:
      - name: local
        platform: linux/arm64
