actions:
  fix-sshd-host-key-permissions: chmod 600 /etc/ssh/ssh_host*
  fix-ssh_config-permissions: chmod 600 config/ssh/config
config:
  banner: false
  dotpath: config
  link_dotfile_default: link
  link_on_import: link
trans_read:
  _decrypt:
    openssl enc -aes-256-cbc -nosalt -d -pbkdf2 -in {0} -out {1} -pass pass:{{@@
    env['SECRET'] @@}}
trans_write:
  _encrypt:
    openssl enc -aes-256-cbc -nosalt -pbkdf2 -in {0} -out {1} -pass pass:{{@@
    env['SECRET'] @@}}
dotfiles:
  apt-proxy:
    dst: /etc/apt/apt.conf.d/proxy
    link: nolink
    src: apt/proxy
  bash_logout:
    dst: ~/.bash_logout
    src: bash/bash_logout
  bashrc:
    dst: ~/.bashrc
    src: bash/bashrc
  bat:
    dst: ~/.config/bat
    src: bat
  bazel:
    dst: ~/.bazelrc
    src: bazel/bazelrc
  cargo:
    dst: ~/.cargo
    src: cargo
  ccache:
    dst: ~/.config/ccache
    src: ccache
  clang-format:
    dst: ~/.clang-format
    src: clang-format/clang-format
  cmake-format:
    dst: ~/.cmake-format.json
    src: cmake-format/cmake-format.json
  conan:
    dst: ~/.conan
    src: conan
  conda:
    dst: ~/.condarc
    src: conda/condarc
  crontab:
    dst: /etc/cron.d/custom.crontab
    link: nolink
    src: crontab/custom.crontab
  dircolors:
    dst: ~/.dircolors
    src: ls/dircolors
  docker:
    dst: ~/.docker
    src: docker
  docker-d:
    dst: /etc/docker/daemon.json
    link: nolink
    src: docker/daemon.json
  docker-proxy:
    dst: /etc/systemd/system/docker.service.d/http-proxy.conf
    link: nolink
    src: docker/http-proxy.conf
  dolthub:
    dst: ~/.dolt
    src: dolthub
  gdb:
    dst: ~/.gdbinit
    src: gdb/gdbinit
  git-config:
    dst: ~/.gitconfig
    src: git/.gitconfig
  git-key:
    dst: ~/dotbox/config/ssh/id_rsa-github.origin
    src: ssh/id_rsa-github
    trans_read: _decrypt
    trans_write: _encrypt
    link: nolink
    chmod: '600'
  go:
    dst: ~/.config/go
    src: go
  golangci:
    dst: ~/.golangci.yaml
    src: golangci/golangci.yaml
  goproxy-systemd:
    dst: /lib/systemd/system/goproxy.service
    link: nolink
    src: goproxy/goproxy.service
  gost-d:
    dst: /etc/gost/daemon.json
    link: nolink
    src: gost/daemon.json
  gost-systemd:
    dst: /lib/systemd/system/gost.service
    link: nolink
    src: gost/gost.service
  gradle:
    dst: ~/.gradle
    src: gradle
  helix:
    dst: ~/.config/helix
    src: helix
  httpbin:
    dst: /lib/systemd/system/go-httpbin.service
    link: nolink
    src: httpbin/go-httpbin.service
  hyper:
    dst: ~/.hyper.js
    src: hyper/hyper.js
  isort:
    dst: ~/.isort.cfg
    src: isort/isort.cfg
  jupyter:
    dst: ~/.jupyter
    src: jupyter
  linux-environment:
    dst: /etc/environment
    link: nolink
    src: linux/environment
  linux-journal:
    dst: /etc/systemd/journald.conf
    link: nolink
    src: systemd/journald.conf
  linux-profile:
    dst: /etc/profile.d/custom.sh
    link: nolink
    src: linux/profile.d/custom.sh
  linux-sudoers:
    dst: /etc/sudoers.d/custom
    link: nolink
    src: linux/sudoers.d/custom
  linux-sysctl-1:
    dst: /etc/sysctl.d/10-ptrace.conf
    link: nolink
    src: linux/sysctl.d/10-ptrace.conf
  linux-sysctl-2:
    dst: /etc/sysctl.d/custom.conf
    link: nolink
    src: linux/sysctl.d/custom.conf
  markdownlint:
    dst: ~/.markdownlintrc
    src: markdownlint/markdownlintrc
  maven:
    dst: ~/.m2
    src: maven
  navi:
    dst: ~/.config/navi
    src: navi
  navi-cheats:
    dst: ~/.local/share/navi/cheats/local
    src: navi-cheats
  neofetch:
    dst: ~/.config/neofetch
    src: neofetch
  pip:
    dst: ~/.config/pip
    src: pip
  prettier:
    dst: ~/.prettierrc.yaml
    src: prettier/prettierrc.yaml
  procps:
    dst: ~/.config/procps
    src: procps
  profile:
    dst: ~/.profile
    src: bash/profile
  pylintrc:
    dst: ~/.config/pylintrc
    src: pylint/pylintrc
  rime:
    dst: ~/Library/Rime
    src: rime/squirrel
  rubocop:
    dst: ~/.rubocop.yml
    src: rubocop/rubocop.yml
  shellcheck:
    dst: ~/.shellcheckrc
    src: shellcheck/shellcheckrc
  snipaste:
    dst: ~/.snipaste/config.ini
    src: snipaste/config.ini
  ssh-authorized-key:
    dst: ~/.ssh/authorized_keys
    src: ssh/authorized_keys
  ssh-d:
    dst: /etc/ssh/sshd_config.d/custom.conf
    link: nolink
    src: ssh/sshd-custom.conf
  ssh-host-key:
    actions:
      - fix-sshd-host-key-permissions
    dst: /etc/ssh
    link: nolink
    src: ssh/host-key
  ssh-config:
    dst: ~/.ssh/config
    actions:
      - fix-ssh_config-permissions
    src: ssh/config
  startship:
    dst: ~/.config/starship.toml
    src: starship/starship.toml
  tabby:
    dst: ~/Library/Application Support/tabby
    src: tabby
  terminalizer:
    dst: ~/.terminalizer
    src: terminalizer
  tmux:
    dst: ~/.tmux.conf
    src: tmux/tmux.conf
  tmux-local:
    dst: ~/.tmux.conf.local
    src: tmux/tmux.conf.local
  vimrc:
    dst: ~/.vimrc
    src: vim/vimrc
  vscode:
    dst: ~/Library/Application Support/Code/User
    src: vscode/app
  vscode-server:
    dst: ~/.vscode-server/data/Machine/settings.json
    src: vscode/remote-server-settings.json
  vscode-remote:
    dst: ~/.vscode-remote/data/Machine/settings.json
    src: vscode/remote-server-settings.json
  yapf:
    dst: ~/.style.yapf
    src: yapf/style.yapf
  yarn:
    dst: ~/.yarnrc
    src: yarn/yarnrc
  zprofile:
    dst: ~/.zprofile
    src: zsh/zprofile
  zshrc:
    dst: ~/.zshrc
    src: zsh/zshrc
profiles:
  sysconf:
    dotfiles:
      - docker-d
      - linux-environment
      - linux-journal
      - linux-profile
      - linux-sudoers
      - linux-sysctl-1
      - linux-sysctl-2
      - ssh-d
      - ssh-host-key

  sysconf-proxy:
    dotfiles:
      - apt-proxy
      - docker-proxy

  image:
    dotfiles:
      - bazel
      - cargo
      - clang-format
      - conan
      - conda
      - docker
      - dolthub
      - git-config
      - gradle
      - helix
      - isort
      - maven
      - prettier
      - procps
      - profile
      - ssh-authorized-key
      - ssh-config
      - tmux
      - vimrc
      - vscode-remote
      - vscode-server
      - yapf
      - zprofile
      - zshrc

  darwin:
    dotfiles:
      - helix
      - prettier
      - profile
      - ssh-authorized-key
      - yapf
      - zprofile
      - zshrc
      # GUI-APP
      - hyper
      - rime
      - snipaste
      - vscode
