version: '3'

tasks:
  _build:
    cmds:
      - docker build .
        --file ./Dockerfile
        --network=host
        --build-arg="PYTHON_VERSION={{.version}}"
        --tag curoky/devspace:prebuilt-python-{{.version}}
  3.8.20:
    deps:
      - task: _build
        vars:
          version: 3.8.20
  3.9.23:
    deps:
      - task: _build
        vars:
          version: 3.9.23
  3.10.18:
    deps:
      - task: _build
        vars:
          version: 3.10.18
  3.11.13:
    deps:
      - task: _build
        vars:
          version: 3.11.13
  3.12.11:
    deps:
      - task: _build
        vars:
          version: 3.12.11
  3.13.7:
    deps:
      - task: _build
        vars:
          version: 3.13.7
  all_parallel:
    deps:
      - 3.13.7
      - 3.12.11
      - 3.11.13
      - 3.10.18
      - 3.9.23
      - 3.8.20
  all:
    - task: 3.13.7
    - task: 3.12.11
    - task: 3.11.13
    - task: 3.10.18
    - task: 3.9.23
    - task: 3.8.20
    # - docker push curoky/devspace:prebuilt-python-3.8.20
    # - docker push curoky/devspace:prebuilt-python-3.9.23
    # - docker push curoky/devspace:prebuilt-python-3.10.18
    # - docker push curoky/devspace:prebuilt-python-3.11.13
    # - docker push curoky/devspace:prebuilt-python-3.12.11
    # - docker push curoky/devspace:prebuilt-python-3.13.7
