#!/usr/bin/env bash

script_path="$(readlink -f "$0")"
root=$(cd "$(dirname "$script_path")" && pwd)/..
pkgs=$root/pkgs

exec -a "$0" "$pkgs/file/bin/file" "--magic-file" "$pkgs/file/share/misc/magic.mgc" "$@"
