#!/usr/bin/env bash

script_path="$(readlink -f "$0")"
root=$(cd "$(dirname "$script_path")" && pwd)/..
pkgs=$root/pkgs

export FPATH=$FPATH:$pkgs/zsh/share/zsh/5.9/functions

exec -a "$0" "$pkgs/zsh/bin/zsh" "$@"
