#!/usr/bin/env bash

root=$(cd "$(dirname "$0")" && pwd)/..
if [[ -z $GIT_TEMPLATE_DIR ]]; then
  export GIT_TEMPLATE_DIR="$root/share/git-core/templates"
fi

if [[ -z $GIT_EXEC_PATH ]]; then
  export GIT_EXEC_PATH="$root/libexec/git-core"
fi

if [[ -z $GIT_TEXTDOMAINDIR ]]; then
  export GIT_TEXTDOMAINDIR="$root/share/locale"
fi

# export PATH=$PATH:$root/libexec/git-core
exec -a "$0" "$root/bin/.git-wrapped" "$@"
