#!/usr/bin/env bash

root=$(cd "$(dirname "$0")" && pwd)/..

export PYTHONHOME=$root/py311-static
export PYTHONPATH=$PYTHONPATH:$PYTHONHOME/lib/python3.11
export PYTHONPATH=$PYTHONPATH:$PYTHONHOME/lib/python3.11/site-packages
export PYTHONPATH=$PYTHONPATH:$PYTHONHOME/lib/python3.11/lib-dynload
export PYTHONPATH=$PYTHONPATH:$root/pipx/venvs/netron/lib/python3.11/site-packages

# python_bin_path=/home/x/.nix-profile/bin/python3.11
# pathon_lib_root=/nix/var/nix/profiles/py311-static/lib/python3.11/

exec -a "$0" "$PYTHONHOME/bin/python3" "$root/pipx/venvs/netron/bin/netron" "$@"
