#!/usr/bin/env bash

script_path="$(readlink -f "$0")"
root=$(cd "$(dirname "$script_path")" && pwd)/../py311

# root=/home/x/app/prebuilt/py311
python_bin_path=$root/bin/python3
pathon_lib_root=$root/lib/python3.11

export PYTHONHOME=$root
export PYTHONPATH=$pathon_lib_root:$pathon_lib_root/site-packages:$pathon_lib_root/lib-dynload
exec -a "$0" "$python_bin_path" "$@"
