#!/usr/bin/env bash

# https://askubuntu.com/questions/445686/vim-cannot-find-syntax-vim

root=$(cd "$(dirname "$0")" && pwd)/../inner
export VIMRUNTIME=$root/share/vim/vim91

exec -a "$0" "$root/bin/vim" "$@"
