#!/usr/bin/env bash

# https://askubuntu.com/questions/445686/vim-cannot-find-syntax-vim

script_path="$(readlink -f "$0")"
root=$(cd "$(dirname "$script_path")" && pwd)/../inner

if [[ -z $VIMRUNTIME ]]; then
  export VIMRUNTIME=$root/share/vim/vim91
fi

# args=""
# if [[ -f $HOME/dotbox/config/vim/vimrc ]]; then
#   args="-u $HOME/dotbox/config/vim/vimrc"
# elif [[ -f $HOME/app/sre-tools/dotbox/config/vim/vimrc ]]; then
#   args="-u $HOME/app/sre-tools/dotbox/config/vim/vimrc"
# fi

exec -a "$0" "$root/bin/vim" "$@"
