version: '3'

tasks:
  tf2.5-cu11.0-abi0:
    cmds:
      - >
        docker buildx build .
        --file 2.5.0/Dockerfile.cu11.0.3-cudnn8.1.0-gcc8-py3.7
        --network=host
        --build-arg USE_CXX11_ABI=0
        --tag curoky/dotbox:stage-tf2.5.0-cu11.0.3-cudnn8.1.0-gcc8-py3.7-abi0
  tf2.5-cu11.0-abi1:
    cmds:
      - >
        docker buildx build .
        --file 2.5.0/Dockerfile.cu11.0.3-cudnn8.1.0-gcc8-py3.7
        --network=host
        --build-arg USE_CXX11_ABI=1
        --tag curoky/dotbox:stage-tf2.5.0-cu11.0.3-cudnn8.1.0-gcc8-py3.7-abi1
  tf2.5-cu11.4-abi0:
    cmds:
      - >
        docker buildx build .
        --file 2.5.0/Dockerfile.cu11.4.0-cudnn8.1.0-gcc8-py3.7
        --network=host
        --build-arg USE_CXX11_ABI=0
        --tag curoky/dotbox:stage-tf2.5.0-cu11.4.0-cudnn8.1.0-gcc8-py3.7-abi0
  tf2.5-cu11.4-abi1:
    cmds:
      - >
        docker buildx build .
        --file 2.5.0/Dockerfile.cu11.4.0-cudnn8.1.0-gcc8-py3.7
        --network=host
        --build-arg USE_CXX11_ABI=1
        --tag curoky/dotbox:stage-tf2.5.0-cu11.4.0-cudnn8.1.0-gcc8-py3.7-abi1
  tf2.16-cu12.3:
    cmds:
      - >
        docker buildx build .
        --file 2.16.1/Dockerfile.cu12.3.2-cudnn8.9.7-gcc11-py3.11
        --network=host
        --tag curoky/dotbox:stage-tf2.16.1-cu12.3.2-cudnn8.9.7-gcc11-py3.11
