# tap 'ecopastehub/ecopaste'

# brew list --cask | xargs -n 1 | sort -u | awk '{ print "\x27"$1"\x27""," }'
casks = [
  'font-fira-code-nerd-font',
  'font-lxgw-wenkai',
  'font-ubuntu-mono-nerd-font',
  'iina',
  'istat-menus@6',
  'snipaste',
  'keepingyouawake',
  'input-source-pro',
  'freefilesync',
  'resilio-sync',
  'secretive',
  'obs',
  'gimp',
  'finetune',

  # 'cap',
  # 'clash-verge-rev',
  # 'sloth',
  # 'localsend',
  # 'flameshot',

  # 'squirrel-app',
  # 'drawio',
  # 'google-drive',
  # 'dupeguru',
  # 'adrive',
  # 'kap',
  # 'keycastr',
  # 'pika',
  # 'miniconda',
  # 'ecopaste',
  # 'orbstack',
  # 'db-browser-for-sqlite',
  # 'only-switch',
  # 'stats',
  # 'android-platform-tools',
  # 'charles',
  # 'chromedriver',
  # 'dbeaver-community',
  # 'disk-drill',
  # 'motrix',
  # 'netnewswire',
  # 'sketch',
  # 'sqlitestudio',
  # 'webtorrent',
  # 'firefox',
  # 'visual-studio-code',
  # 'warp',
  # 'google-chrome',
  # 'lyricsx', # https://github.com/ddddxxx/LyricsX
]

casks.each do |b|
  cask b
end

brews = [
  'bash',
  'bats-core',
  'clang-format',
  'python@3',
  'go',
  'node',
  'podman',
  'shellcheck',
  'shfmt',
  # 'pre-commit', 'prettier', 'eslint',
  # 'wget',
  # 'smartmontools',
  # 'parallel',
  # 'exiftool',
  # 'pnpm',
  # 'ffmpeg',

  # 'krb5',
  # 'openjdk',
  # 'git',
  # 'yazi',
  # 'colima', 'docker', 'qemu',

  # rust
  # 'uv', 'ruff', 'eza', 'bat', 'atuin', 'fd', 'git-absorb', 'starship',

  # go
  # 'git-lfs', 'gost', 'fzf', 'go-task',

  # compression
  # 'bzip2', 'xz', 'zstd', 'zip', 'unzip',

  # network tools
  # 'netcat', 'lsof', 'connect', 'inetutils',

  # text editor and tools
  # 'gettext', 'm4', 'gpatch', 'the_silver_searcher',

  # others
  # 'aria2',
  # 'rsync',
  # 'ncdu',
  # 'coreutils',
]

brews.each do |b|
  brew b
end
