#!/usr/bin/env bash

set -xeuo pipefail

exec > >(sudo tee /var/log/oncetask.log) 2>&1

# clean cache
rm -rf /home/x/.cache/starship.plugin.zsh \
  /home/x/.cache/conda.plugin.zsh \
  /home/x/.cache/atuin.plugin.zsh

sudo -E /opt/devspace/images/base/script/setup-proxy.sh

mkdir -p /workspace/.vscode-server/data/Machine
ln -sf /home/x/.vscode-server/data/Machine/settings.json /workspace/.vscode-server/data/Machine/settings.json

mkdir -p /workspace/.trae-server
rm -rf /home/x/.trae-server
ln -sf /workspace/.trae-server /home/x/.trae-server
mkdir -p /home/x/.trae-server/data/Machine
ln -sf /home/x/.vscode-server/data/Machine/settings.json /home/x/.trae-server/data/Machine/settings.json

if [[ -d /workspace/ai-coding-config/.trae/rules ]]; then
  rsync --partial --progress --archive --human-readable --rsh=ssh --delete --delete-excluded \
    /workspace/ai-coding-config/.trae/rules/ /home/x/.trae/user_rules/
fi

if [[ -f /workspace/passkey/run.sh ]]; then
  bash /workspace/passkey/run.sh
fi

# /opt/devspace/tools/profile-installer.sh --ssl-pass-src pass:"$PROFILE_PASS"
# /opt/devspace/dotfiles/passkey/profile.gzip.sh --ssl-pass-src pass:"$PROFILE_PASS"
# bash /home/x/.config/atuin/login-and-sync.sh &

# export PATH=$PATH:/opt/rust/cargo/bin:/opt/sb/bin
# /opt/devspace/images/base/stage/uv/conda/install.sh py3 &


# ollama pull llama3:8b &
# ollama pull mistral &

# wait
