actions:
  fix-sshd-host-key-permissions: chmod 600 /etc/ssh/sshd-host-key/*
  fix-ssh-config-permissions: chmod 600 config/ssh/ssh_config
  fix-user-ssh-config-permissions: chmod 600 ~/.ssh/config
config:
  banner: false
  dotpath: .
  link_dotfile_default: link
  link_on_import: link
  template_dotfile_default: false
  minversion: 1.14.0
dotfiles:
  atuin:
    dst: ~/.config/atuin/config.toml
    src: atuin/config.toml
  bashrc:
    dst: ~/.bashrc
    src: bash/bashrc
  bazel:
    dst: ~/.bazelrc
    src: bazel/bazelrc
  cargo:
    dst: ~/.cargo/config.toml
    src: cargo/config.toml
  ccache:
    dst: ~/.config/ccache/ccache.conf
    src: ccache/ccache.conf
  conan2:
    dst: ~/.conan2/global.conf
    src: conan2/global.conf
  conda:
    dst: ~/.config/conda/condarc
    src: conda/condarc
  croc:
    dst: ~/.config/croc
    src: croc
  docker:
    dst: ~/.docker/config.json
    src: docker/config.json
  gdb:
    dst: ~/.gdbinit
    src: gdb/gdbinit
  git-config:
    link: nolink
    dst: ~/.gitconfig
    src: git/.gitconfig
  go:
    dst: ~/.config/go
    src: go
  golangci:
    dst: ~/.golangci.yaml
    src: golangci/golangci.yaml
  gradle:
    dst: ~/.gradle/gradle.properties
    src: gradle/gradle.properties
  jupyter:
    dst: ~/.jupyter
    src: jupyter
  maven:
    dst: ~/.m2/settings.xml
    src: maven/settings.xml
  nixpkgs:
    dst: ~/.config/nixpkgs/config.nix
    src: nixpkgs/config.nix
  pip:
    dst: ~/.config/pip
    src: pip
  prettier:
    dst: ~/.prettierrc.yaml
    src: prettier/prettierrc.yaml
  top:
    dst: ~/.config/procps/toprc
    src: procps/toprc
  rime:
    dst: ~/Library/Rime
    src: rime/squirrel
  snipaste:
    dst: ~/.snipaste/config.ini
    src: snipaste/config.ini
  ssh-authorized-key:
    link: nolink
    dst: ~/.ssh/authorized_keys
    src: ssh/authorized_keys
    chmod: 600
  ssh-user-config:
    dst: ~/.ssh/config
    chmod: 600
    src: ssh/user.ssh_config
    link: nolink
  startship:
    dst: ~/.config/starship.toml
    src: starship/starship.toml
  tabby:
    dst: ~/Library/Application Support/tabby
    src: tabby
  terminalizer:
    dst: ~/.terminalizer
    src: terminalizer
  tmux:
    dst: ~/.tmux.conf
    src: tmux/tmux.conf
  tmux-local:
    dst: ~/.tmux.conf.local
    src: tmux/tmux.conf.local
  vim:
    dst: ~/.vimrc
    src: vim/vimrc
  vscode-snippets:
    dst: ~/Library/Application Support/Code/User/snippets
    src: vscode/app/snippets
  vscode-keybindings:
    dst: ~/Library/Application Support/Code/User/keybindings.json
    src: vscode/app/keybindings.json
  vscode-settings:
    dst: ~/Library/Application Support/Code/User/settings.json
    src: vscode/app/settings.json
  vscode-server:
    dst: ~/.vscode-server/data/Machine/settings.json
    src: vscode/remote-server-settings.json
  yarn:
    dst: ~/.yarnrc
    src: yarn/yarnrc
  zshrc:
    dst: ~/.zshrc
    link: nolink
    src: zsh/prune.zshrc
profiles:
  docker:
    dotfiles:
      - bashrc
      # - bazel
      - conda
      - croc
      - gdb
      - nixpkgs
      # - prettier
      - top
      # - tmux
      - vim
      - vscode-server
      - git-config
      - ssh-user-config
      - zshrc

  macos:
    dotfiles:
      # - prettier
      - atuin
      - conda
      - top
      - rime
      - snipaste
      - vim
      - vscode-keybindings
      - vscode-settings
      - vscode-snippets
      - git-config
      - ssh-user-config
      - zshrc
