# syntax=docker/dockerfile:1.9.0
FROM ubuntu:24.04 AS builder

#### Common start ####
RUN apt-get update -y \
  && apt-get install -y \
    curl wget git ncdu ca-certificates xz-utils patchelf

# install clang
RUN apt-get install -y clang-17 lld-17

# install python
RUN apt-get install -y python3.12 python3.12-dev python3-pip

# install bazel
RUN curl -sSL -o bazelisk https://github.com/bazelbuild/bazelisk/releases/download/v1.20.0/bazelisk-linux-amd64 \
  && chmod +x bazelisk \
  && mv bazelisk /usr/local/bin/bazel
#### Common end ####

COPY --link --from=curoky/dotbox:stage-cuda-cu12.3.2-cudnn8.9.7 /home/x/app/nvidia/cuda-12.3.2 /home/x/app/nvidia/cuda-12.3.2
COPY --link --from=curoky/dotbox:stage-cuda-cu12.3.2-cudnn8.9.7 /home/x/app/nvidia/cudnn8.9.7-cu12 /home/x/app/nvidia/cudnn8.9.7-cu12

RUN git clone --recurse-submodules --depth=1 -b v2.16.1 https://github.com/tensorflow/tensorflow
WORKDIR /tensorflow

RUN cat <<EOF >> .bazelrc
startup --host_jvm_args=-Djava.net.preferIPv6Addresses=true

# for clang
build --repo_env=CC=/usr/lib/llvm-17/bin/clang
build --repo_env=BAZEL_COMPILER=/usr/lib/llvm-17/bin/clang
build --action_env CLANG_CUDA_COMPILER_PATH=/usr/lib/llvm-17/bin/clang
build --action_env CLANG_COMPILER_PATH=/usr/lib/llvm-17/bin/clang
build --copt=-Wno-gnu-offsetof-extensions
build --copt=-Wno-unused-command-line-argument

# for python
build --python_path="/usr/bin/python3.12"
build --action_env TF_PYTHON_VERSION="3.12"
build --action_env PYTHON_BIN_PATH="/usr/bin/python3.12"
build --action_env PYTHON_LIB_PATH="/usr/lib/python3.12/site-packages"
build --repo_env=WHEEL_NAME=tensorflow

# for cuda
build:cuda --action_env TF_NEED_CUDA=1
build:cuda --action_env TF_CUDA_CLANG=1
build:cuda --action_env TF_CUDA_VERSION="12.3"
build:cuda --action_env TF_CUDNN_VERSION="8"
build:cuda --action_env TF_CUDA_COMPUTE_CAPABILITIES="sm_75,compute_75,sm_80,compute_80,sm_86,compute_86"
build:cuda --action_env TF_CUDA_PATHS="/home/x/app/nvidia/cuda-12.3.2"
build:cuda --action_env CUDA_TOOLKIT_PATH="/home/x/app/nvidia/cuda-12.3.2"
build:cuda --action_env CUDNN_INSTALL_PATH="/home/x/app/nvidia/cudnn8.9.7-cu12"
build:cuda --@local_config_cuda//:cuda_compiler=clang
# build:cuda --repo_env HERMETIC_CUDA_VERSION="12.3"
# build:cuda --repo_env HERMETIC_CUDNN_VERSION="8"
# build:cuda --repo_env HERMETIC_CUDA_COMPUTE_CAPABILITIES="sm_75,compute_75,sm_80,compute_80,sm_86,compute_86"
# build:cuda --repo_env LOCAL_CUDA_PATH="/home/x/app/nvidia/cuda-12.3.2"
# build:cuda --repo_env LOCAL_CUDNN_PATH="/home/x/app/nvidia/cudnn8.9.7-cu12"

EOF

RUN bazel build //tensorflow/tools/pip_package:build_pip_package \
    --config=v2 \
    # --config=opt \
    --config=avx_linux \
    --config=monolithic \
    # --config=tensorrt \
    --config=cuda \
    # --config=cuda_clang \
    --config=noaws \
    --config=nogcp \
    --config=nohdfs \
    --config=nonccl
RUN ./bazel-bin/tensorflow/tools/pip_package/build_pip_package /output

FROM debian:latest

COPY --from=builder /output /output

RUN ls -lah /output/tensorflow-2.16.1-cp312-cp312-linux_x86_64.whl
