default_image: ghcr.io/curoky/devspace:codespace-debian13

hosts:
  local:
    type: podman-machine
    machine: podman-machine-default

tokens:
  github: github_pat_
  gitlab: glpat

projects:
  devspace:
    host: local
    repo: github:curoky/devspace
    platform: linux/arm64

  standalone-binaries:
    host: local
    repo: github:curoky/standalone-binaries
    platform: linux/arm64

  agent-playbook:
    host: local
    repo: github:curoky/agent-playbook
    platform: linux/arm64

  obsidian:
    host: local
    repo: github:curoky/obsidian
    platform: linux/arm64

  rss:
    host: local
    repo: github:curoky/rss
    platform: linux/arm64
