version: '3'

tasks:
  11.0:
    cmds:
      - >
        docker buildx build .
        --file Dockerfile
        --build-arg="CUDA_VERSION=11.0.3"
        --build-arg="DRIVER_VERSION=450.51.06"
        --build-arg="CUDNN_VERSION=8.1.0.77_cuda11"
        --network=host
        --tag curoky/dotbox:stage-cuda-11.0
  11.4:
    cmds:
      - >
        docker buildx build .
        --file Dockerfile
        --build-arg="CUDA_VERSION=11.4.0"
        --build-arg="DRIVER_VERSION=470.42.01"
        --build-arg="CUDNN_VERSION=8.1.0.77_cuda11"
        --network=host
        --tag curoky/dotbox:stage-cuda-11.4
  12.3:
    cmds:
      - >
        docker buildx build .
        --file Dockerfile
        --build-arg="CUDA_VERSION=12.3.2"
        --build-arg="DRIVER_VERSION=545.23.08"
        --build-arg="CUDNN_VERSION=8.9.7.29_cuda12"
        --network=host
        --tag curoky/dotbox:stage-cuda-12.3
