# https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#create-env-file-manually
name: py3
channels:
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - ipykernel
      - ipywidgets
      - pydantic
      - requests
      - typer
      - icalendar
      # - python-snappy==0.6.1
      - locust
      - sqlmodel
      - bbpb
      - notion-client
      - git+https://github.com/curoky/thriftpy2@dev
      - git+https://github.com/curoky/thriftoy@dev
