# https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#create-env-file-manually
name: pipx
channels:
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
      - pipx
