# https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#create-env-file-manually
name: py311
channels:
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - ipykernel
      - ipywidgets
      - pydantic
      - requests
      - typer
