numbered_mode_switch:
  __append:
    - { when: always, accept: Control+Shift+1, select: .next }
    - { when: always, accept: Control+Shift+3, toggle: emoji_suggestion }
    - { when: always, accept: Control+Shift+4, toggle: symbol_support }
    - { when: always, accept: Control+Shift+5, toggle: ascii_punct }
    - { when: always, accept: Control+Shift+exclam, select: .next }
    - {
        when: always,
        accept: Control+Shift+numbersign,
        toggle: emoji_suggestion,
      }
    - { when: always, accept: Control+Shift+dollar, toggle: symbol_support }
    - { when: always, accept: Control+Shift+percent, toggle: ascii_punct }

windows_compatible_mode_switch:
  __append:
    - { when: always, accept: Control+comma, toggle: ascii_punct }
    - { when: always, accept: Control+period, toggle: ascii_punct }

kp_enter_is_return:
  __append:
    - { when: has_menu, accept: KP_Enter, send: Return }
