name: clover
version: '1'
sort: by_weight

import_tables:
  # - custom
  - ../../../../../app/sre-tools/pkgs/rime-bundle/share/rime-bundle/rime-ice/cn_dicts/8105
  - ../../../../../app/sre-tools/pkgs/rime-bundle/share/rime-bundle/rime-ice/cn_dicts/base
  - ../../../../../app/sre-tools/pkgs/rime-bundle/share/rime-bundle/rime-ice/cn_dicts/ext
  - ../../../../../app/sre-tools/pkgs/rime-bundle/share/rime-bundle/rime-ice/cn_dicts/41448
  - ../../../../../app/sre-tools/pkgs/rime-bundle/share/rime-bundle/rime-ice/cn_dicts/tencent

  - ../../../../../app/sre-tools/pkgs/rime-bundle/share/rime-bundle/rime-cloverpinyin/THUOCL_animal
  - ../../../../../app/sre-tools/pkgs/rime-bundle/share/rime-bundle/rime-cloverpinyin/THUOCL_caijing
  - ../../../../../app/sre-tools/pkgs/rime-bundle/share/rime-bundle/rime-cloverpinyin/THUOCL_car
  - ../../../../../app/sre-tools/pkgs/rime-bundle/share/rime-bundle/rime-cloverpinyin/THUOCL_chengyu
  - ../../../../../app/sre-tools/pkgs/rime-bundle/share/rime-bundle/rime-cloverpinyin/THUOCL_diming
  - ../../../../../app/sre-tools/pkgs/rime-bundle/share/rime-bundle/rime-cloverpinyin/THUOCL_food
  - ../../../../../app/sre-tools/pkgs/rime-bundle/share/rime-bundle/rime-cloverpinyin/THUOCL_IT
  - ../../../../../app/sre-tools/pkgs/rime-bundle/share/rime-bundle/rime-cloverpinyin/THUOCL_law
  - ../../../../../app/sre-tools/pkgs/rime-bundle/share/rime-bundle/rime-cloverpinyin/THUOCL_lishimingren
  - ../../../../../app/sre-tools/pkgs/rime-bundle/share/rime-bundle/rime-cloverpinyin/THUOCL_medical
  - ../../../../../app/sre-tools/pkgs/rime-bundle/share/rime-bundle/rime-cloverpinyin/THUOCL_poem

  - ../../../../../app/sre-tools/pkgs/rime-bundle/share/rime-bundle/rime-cloverpinyin/clover.base
  - ../../../../../app/sre-tools/pkgs/rime-bundle/share/rime-bundle/rime-cloverpinyin/clover.phrase

  # - ../../../../../app/sre-tools/pkgs/rime-bundle/share/rime-bundle/rime-dict/simple.luna_pinyin.anime
  - ../../../../../app/sre-tools/pkgs/rime-bundle/share/rime-bundle/rime-dict/simple.luna_pinyin.basis
  - ../../../../../app/sre-tools/pkgs/rime-bundle/share/rime-bundle/rime-dict/simple.luna_pinyin.biaoqing
  - ../../../../../app/sre-tools/pkgs/rime-bundle/share/rime-bundle/rime-dict/simple.luna_pinyin.chat
  - ../../../../../app/sre-tools/pkgs/rime-bundle/share/rime-bundle/rime-dict/simple.luna_pinyin.classical
  # - ../../../../../app/sre-tools/pkgs/rime-bundle/share/rime-bundle/rime-dict/simple.luna_pinyin.cn_en
  - ../../../../../app/sre-tools/pkgs/rime-bundle/share/rime-bundle/rime-dict/simple.luna_pinyin.computer
  - ../../../../../app/sre-tools/pkgs/rime-bundle/share/rime-bundle/rime-dict/simple.luna_pinyin.daily
  # - ../../../../../app/sre-tools/pkgs/rime-bundle/share/rime-bundle/rime-dict/simple.luna_pinyin.diet
  # - ../../../../../app/sre-tools/pkgs/rime-bundle/share/rime-bundle/rime-dict/simple.luna_pinyin.game
  # - ../../../../../app/sre-tools/pkgs/rime-bundle/share/rime-bundle/rime-dict/simple.luna_pinyin.gd
  - ../../../../../app/sre-tools/pkgs/rime-bundle/share/rime-bundle/rime-dict/simple.luna_pinyin.hanyu
  - ../../../../../app/sre-tools/pkgs/rime-bundle/share/rime-bundle/rime-dict/simple.luna_pinyin.history
  - ../../../../../app/sre-tools/pkgs/rime-bundle/share/rime-bundle/rime-dict/simple.luna_pinyin.idiom
  # - ../../../../../app/sre-tools/pkgs/rime-bundle/share/rime-bundle/rime-dict/simple.luna_pinyin.moba
  # - ../../../../../app/sre-tools/pkgs/rime-bundle/share/rime-bundle/rime-dict/simple.luna_pinyin.movie
  # - ../../../../../app/sre-tools/pkgs/rime-bundle/share/rime-bundle/rime-dict/simple.luna_pinyin.music
  - ../../../../../app/sre-tools/pkgs/rime-bundle/share/rime-bundle/rime-dict/simple.luna_pinyin.name
  - ../../../../../app/sre-tools/pkgs/rime-bundle/share/rime-bundle/rime-dict/simple.luna_pinyin.net
  - ../../../../../app/sre-tools/pkgs/rime-bundle/share/rime-bundle/rime-dict/simple.luna_pinyin.poetry
  - ../../../../../app/sre-tools/pkgs/rime-bundle/share/rime-bundle/rime-dict/simple.luna_pinyin.practical
  - ../../../../../app/sre-tools/pkgs/rime-bundle/share/rime-bundle/rime-dict/simple.luna_pinyin.sougou
  - ../../../../../app/sre-tools/pkgs/rime-bundle/share/rime-bundle/rime-dict/simple.luna_pinyin.website
