distribution_code_name: Squirrel
distribution_name: '鼠鬚管'
distribution_version: 0.18
install_time: 'Sat Jan 30 03:37:53 2021'
installation_id: rime
rime_version: 1.11.2
sync_dir: '/Users/m/Library/Mobile Documents/com~apple~CloudDocs/backup'
update_time: 'Mon May  6 17:12:28 2024'
