distribution_code_name: Squirrel
distribution_name: '鼠鬚管'
distribution_version: 0.15.2
install_time: 'Sat Jan 30 03:37:53 2021'
installation_id: rime
rime_version: 1.7.3
sync_dir: '/Users/cicada/repos/backup'
update_time: 'Tue Feb 16 14:10:29 2021'
