distribution_code_name: Squirrel
distribution_name: '鼠鬚管'
distribution_version: 1.0.3
install_time: 'Sat Jan 30 03:37:53 2021'
installation_id: rime
rime_version: 1.13.0
sync_dir: '/Users/x/workspace/backup'
update_time: 'Sat Feb  1 17:08:43 2025'
