distribution_code_name: Squirrel
distribution_name: '鼠鬚管'
distribution_version: 1.0.2
install_time: 'Sat Jan 30 03:37:53 2021'
installation_id: rime
rime_version: 1.11.2
sync_dir: '/Users/m/Library/Mobile Documents/com~apple~CloudDocs/backup'
update_time: 'Mon Jul  1 10:52:06 2024'
