# Rime dictionary
# encoding: utf-8
#
# 挂载英文输入方案的词库
#

---
name: melt_eng
version: '1'
import_tables:
  - ../../../../../prebuilt/share/rime-bundle/rime-ice/en_dicts/en_ext
  - ../../../../../prebuilt/share/rime-bundle/rime-ice/en_dicts/en
