# Rime dictionary
# encoding: utf-8
#
# 挂载英文输入方案的词库
#

---
name: melt_eng
version: '1'
import_tables:
  - ../../../../../../../opt/homebrew/opt/rime-bundle/dicts/rime-ice/en_dicts/en_ext
  - ../../../../../../../opt/homebrew/opt/rime-bundle/dicts/rime-ice/en_dicts/en
