#!/usr/bin/env bash

script_path="$(readlink -f "$0")"
root=$(cd "$(dirname "$script_path")" && pwd)/..

exec -a "$0" "$root/bin/dot-wget-wrapped" --ca-certificate $root/../cacert/etc/ssl/certs/ca-certificates.crt "$@"
