# syntax=docker/dockerfile:1.9.0
FROM nixpkgs/nix-unstable:latest AS nixpkgs-builder

ENV NIX_PATH=nixpkgs=channel:nixpkgs-unstable

RUN nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs \
  && nix-channel --update

RUN nix-env -p /nix/var/nix/profiles/llvm -iA nixpkgs.pkgsStatic.llvmPackages_18.clang-unwrapped
