version: '3'

tasks:
  default:
    cmds:
      - >
        docker buildx build .
        --build-context third-party=../../../third-party
        --file Dockerfile
        --network=host
        --tag curoky/dotbox:stage-prebuilt
  llvm18:
    cmds:
      - >
        docker buildx build .
        --build-context third-party=../../../third-party
        --file Dockerfile.llvm18
        --network=host
        --tag curoky/dotbox:stage-prebuilt-llvm18
  rust:
    cmds:
      - >
        docker buildx build .
        --build-context third-party=../../../third-party
        --file Dockerfile.rust
        --network=host
        --tag curoky/dotbox:stage-prebuilt-rust
