version: '3'

tasks:
  default:
    cmds:
      - >
        docker buildx build .
        --build-context third-party=../../../third-party
        --file Dockerfile
        --network=host
        --tag curoky/dotbox:stage-prebuilt
  base:
    cmds:
      - >
        docker buildx build .
        --build-context third-party=../../../third-party
        --file Dockerfile.base
        --network=host
        --tag curoky/dotbox:stage-prebuilt-base
  llvm17:
    cmds:
      - >
        docker buildx build .
        --build-context third-party=../../../third-party
        --file Dockerfile.llvm17
        --network=host
        --tag curoky/dotbox:stage-prebuilt-llvm17
  llvm18:
    cmds:
      - >
        docker buildx build .
        --build-context third-party=../../../third-party
        --file Dockerfile.llvm18
        --network=host
        --tag curoky/dotbox:stage-prebuilt-llvm18
  go:
    cmds:
      - >
        docker buildx build .
        --build-context third-party=../../../third-party
        --file Dockerfile.go
        --network=host
        --tag curoky/dotbox:stage-prebuilt-go
  rust:
    cmds:
      - >
        docker buildx build .
        --build-context third-party=../../../third-party
        --file Dockerfile.rust
        --network=host
        --tag curoky/dotbox:stage-prebuilt-rust
  perl:
    cmds:
      - >
        docker buildx build .
        --build-context third-party=../../../third-party
        --file Dockerfile.perl
        --network=host
        --tag curoky/dotbox:stage-prebuilt-perl
  haskell:
    cmds:
      - >
        docker buildx build .
        --build-context third-party=../../../third-party
        --file Dockerfile.haskell
        --network=host
        --tag curoky/dotbox:stage-prebuilt-haskell
  py3:
    cmds:
      - >
        docker buildx build .
        --build-context third-party=../../../third-party
        --file Dockerfile.py3
        --network=host
        --tag curoky/dotbox:stage-prebuilt-py3
  mac:
    cmds:
      - >
        docker buildx build .
        --build-context third-party=../../../third-party
        --file Dockerfile.mac
        --network=host
        --tag curoky/dotbox:stage-prebuilt-mac
