version: '3'

tasks:
  default:
    cmds:
      - >
        docker buildx build .
        --build-context third-party=../../../third-party
        --file Dockerfile
        --network=host
        --tag curoky/dotbox:stage-prebuilt
  llvm17:
    cmds:
      - >
        docker buildx build .
        --build-context third-party=../../../third-party
        --file Dockerfile.llvm17
        --network=host
        --tag curoky/dotbox:stage-prebuilt-llvm17
  llvm18:
    cmds:
      - >
        docker buildx build .
        --build-context third-party=../../../third-party
        --file Dockerfile.llvm18
        --network=host
        --tag curoky/dotbox:stage-prebuilt-llvm18
  rust:
    cmds:
      - >
        docker buildx build .
        --build-context third-party=../../../third-party
        --file Dockerfile.rust
        --network=host
        --tag curoky/dotbox:stage-prebuilt-rust
  perl:
    cmds:
      - >
        docker buildx build .
        --build-context third-party=../../../third-party
        --file Dockerfile.perl
        --network=host
        --tag curoky/dotbox:stage-prebuilt-perl
  py3:
    cmds:
      - >
        docker buildx build .
        --build-context third-party=../../../third-party
        --file Dockerfile.py3
        --network=host
        --tag curoky/dotbox:stage-prebuilt-py3
