[project]
name = "profiling"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.30.1",
    "ipywidgets>=8.1.7",
    "locust>=2.41.3",
    "pydantic>=2.11.10",
    "python-snappy>=0.7.3",
    "requests>=2.32.5",
    "sqlmodel>=0.0.25",
    "thriftool",
    "typer>=0.19.2",
]

[tool.uv.sources]
thriftool = { git = "https://github.com/curoky/thriftool" }
