name: Build images

on:
  push:
  workflow_dispatch:
    inputs:
      disable_docker_cache:
        description: 'disable docker cache'
        default: false
        required: false
        type: boolean

jobs:
  base:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - base_image: 'debian:11'
            saved_image: 'debian11'
          # - base_image: "debian:12"
          #   saved_image: "debian12"
          - base_image: 'ubuntu:24.04'
            saved_image: 'ubuntu24.04'
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: curoky
          password: ${{ secrets.DOCKER_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/base/Dockerfile
          push: true
          cache-from: type=registry,ref=curoky/dotbox:__cache_base_${{ matrix.saved_image }}
          cache-to: type=registry,ref=curoky/dotbox:__cache_base_${{ matrix.saved_image }},mode=max
          no-cache: ${{ github.event_name == 'workflow_dispatch' && inputs.disable_docker_cache == true }}
          build-args: BASE_IMAGE=${{ matrix.base_image }}
          tags: curoky/dotbox:base-${{ matrix.saved_image }}

  stage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        name:
          - conda
          - nixpkg
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: curoky
          password: ${{ secrets.DOCKER_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: docker/stage/${{ matrix.name }}
          build-contexts: |
            third-party=third-party
          file: docker/stage/${{ matrix.name }}/Dockerfile
          push: true
          cache-from: type=registry,ref=curoky/dotbox:__cache_stage_${{ matrix.name }}
          cache-to: type=registry,ref=curoky/dotbox:__cache_stage_${{ matrix.name }},mode=max
          no-cache: ${{ github.event_name == 'workflow_dispatch' && inputs.disable_docker_cache == true }}
          tags: curoky/dotbox:stage-${{ matrix.name }}
  dist:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: default
            base_image: 'debian:11'
            saved_image: default-debian11
          - name: default
            base_image: 'ubuntu:24.04'
            saved_image: default-ubuntu24.04
          - name: tf-gpu
            base_image: 'debian:11'
            saved_image: tf-gpu
          - name: gcc
            base_image: 'debian:11'
            saved_image: gcc
    needs:
      - base
      - stage
    steps:
      - uses: actions/checkout@v4
      # - run: tools/free-github-action-disk-space.sh
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: curoky
          password: ${{ secrets.DOCKER_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: docker/dist/${{ matrix.name }}
          file: docker/dist/${{ matrix.name }}/Dockerfile
          push: true
          cache-from: type=registry,ref=curoky/dotbox:__cache_dist_${{ matrix.saved_image }}
          cache-to: type=registry,ref=curoky/dotbox:__cache_dist_${{ matrix.saved_image }},mode=max
          no-cache: ${{ github.event_name == 'workflow_dispatch' && inputs.disable_docker_cache == true }}
          build-args: BASE_IMAGE=${{ matrix.base_image }}
          tags: curoky/dotbox:${{ matrix.saved_image }}
