name: Build images

on:
  push:
  workflow_dispatch:

jobs:
  stage:
    runs-on: ubuntu-latest
    steps:
      - run: tools/free-github-action-disk-space.sh
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: curoky
          password: ${{ secrets.DOCKER_TOKEN }}

      - uses: docker/build-push-action@v5
        with:
          context: dists/docker/base/debian
          file: dists/docker/base/debian/10.Dockerfile
          push: true
          cache-from: type=registry,ref=curoky/dotbox:stage_debian10
          cache-to: type=inline
          tags: curoky/dotbox:stage_debian10

      - uses: docker/build-push-action@v5
        with:
          context: dists/docker/base/ubuntu
          file: dists/docker/base/ubuntu/24.04.Dockerfile
          push: true
          cache-from: type=registry,ref=curoky/dotbox:stage_ubuntu24.04
          cache-to: type=inline
          tags: curoky/dotbox:stage_ubuntu24.04

      - uses: docker/build-push-action@v5
        with:
          context: dists/docker/base/nixpkg
          build-contexts: |
            nixpkg=third-party/nixpkgs
          file: dists/docker/base/nixpkg/Dockerfile
          push: true
          cache-from: type=registry,ref=curoky/dotbox:stage_nixpkg
          cache-to: type=inline
          tags: curoky/dotbox:stage_nixpkg

      - uses: docker/build-push-action@v5
        with:
          context: dists/docker/base/conda
          file: dists/docker/base/conda/Dockerfile
          push: true
          cache-from: type=registry,ref=curoky/dotbox:stage_conda
          cache-to: type=inline
          tags: curoky/dotbox:stage_conda

      - uses: docker/build-push-action@v5
        with:
          context: dists/docker/base/pipx
          file: dists/docker/base/pipx/Dockerfile
          push: true
          cache-from: type=registry,ref=curoky/dotbox:stage_pipx
          cache-to: type=inline
          tags: curoky/dotbox:stage_pipx
  final:
    runs-on: ubuntu-latest
    needs: stage
    strategy:
      matrix:
        version:
          # - debian9
          - debian10
          - ubuntu24.04
    steps:
      - run: tools/free-github-action-disk-space.sh
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: curoky
          password: ${{ secrets.DOCKER_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: dists/docker/Dockerfile
          push: true
          cache-from: type=registry,ref=curoky/dotbox:${{ matrix.version }}
          cache-to: type=inline
          build-args: BASE_IMAGE=${{ matrix.version }}
          tags: curoky/dotbox:${{ matrix.version }}
