name: Build images

on:
  push:
  schedule:
    - cron: '0 0 28 * *'
  workflow_dispatch:

jobs:
  devbox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: curoky/cleanup-disk-action@master
      - uses: docker/login-action@v2
        with:
          username: curoky
          password: ${{ secrets.DOCKER_TOKEN }}

      - uses: docker/build-push-action@v3
        with:
          context: images
          file: Dockerfile.v3
          push: true
          # cache-from: type=registry,ref=curoky/dotbox:ubuntu22.04
          # cache-to: type=inline
          tags: curoky/dotbox:ubuntu22.04
