name: Build images

on:
  push:
  schedule:
    - cron: '0 0 28 * *'
  workflow_dispatch:

jobs:
  devbox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v1
      - uses: curoky/cleanup-disk-action@master
      - uses: docker/login-action@v1
        with:
          username: curoky
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        run: |
          export BOOTSTRAP_TOKEN=${{ secrets.BOOTSTRAP_TOKEN }}
          ./images/build.sh --push --no-cache=${{ github.event_name == 'schedule' }}
