name: podman

on:
  push:
    paths:
      - '.github/workflows/deps-podman.yaml'
      - 'deps/podman/**'
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - run: ./build.sh
        working-directory: deps/podman

      - uses: svenstaro/upload-release-action@v2
        with:
          file: deps/podman/podman.tar
          asset_name: deps/podman/podman.tar
          tag: 'v1.0'
          overwrite: true

      - uses: mxschmitt/action-tmate@v3
        if: ${{ failure() }}
        timeout-minutes: 30
