name: Dep llvm

on:
  push:
    paths:
      - '.github/workflows/deps-llvm.yaml'
      - 'deps/llvm/**'
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        version:
          - '16.0.6'
          - '17.0.6'
          - '18.1.8'
          - '19.1.7'
          - '20.1.8'
          - '21.1.0'
        enable_2stage:
          - 'true'
          - 'false'
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: curoky
          password: ${{ secrets.DOCKER_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          context: deps/llvm
          file: deps/llvm/Dockerfile
          push: true
          build-args: |
            LLVM_VERSION=${{ matrix.version }}
            ENABLE_2STAGE=${{ matrix.enable_2stage }}
          tags: curoky/devspace:deps-llvm-${{ matrix.version }}-2stage_${{ matrix.enable_2stage }}

      - if: github.event_name == 'schedule'
        run: >
          docker run --rm --env=CI=true -v /var/run/docker.sock:/var/run/docker.sock wagoodman/dive
          curoky/devspace:deps-llvm-${{ matrix.version }}

      - uses: mxschmitt/action-tmate@v3
        if: ${{ failure() }}
        timeout-minutes: 30
