name: Dep python

on:
  push:
    paths:
      - '.github/workflows/deps-python.yaml'
      - 'deps/python/**'
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        version:
          - '3.8.20'
          - '3.9.23'
          - '3.10.18'
          - '3.11.13'
          - '3.12.11'
          - '3.13.7'
          # - '3.14.0'
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: curoky
          password: ${{ secrets.DOCKER_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          context: deps/python
          file: deps/python/Dockerfile
          push: true
          build-args: |
            PYTHON_VERSION=${{ matrix.version }}
          tags: curoky/devspace:deps-python-${{ matrix.version }}

      - if: github.event_name == 'schedule'
        run: >
          docker run --rm --env=CI=true -v /var/run/docker.sock:/var/run/docker.sock wagoodman/dive
          curoky/devspace:deps-python-${{ matrix.version }}

      - uses: mxschmitt/action-tmate@v3
        if: ${{ failure() }}
        timeout-minutes: 30
