name: Login

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ncdu

      - run: tools/free-github-action-disk-space.sh

      - name: save ncdu result
        uses: actions/upload-artifact@v4
        with:
          name: ncdu-result
          path: info.txt

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
