name: Pack prebuilt

on:
  push:
    paths:
      - '.github/workflows/pack-prebuilt.yaml'
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  pack:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - run: sh <(curl -L https://nixos.org/nix/install)

      # - run: |
      #     ~/.nix-profile/nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs
      #     ~/.nix-profile/nix-channel --update

      - run: /nix/var/nix/profiles/default/bin/nix-env -iA nixpkgs.pkgsStatic.xz

      - run: /nix/var/nix/profiles/default/bin/nix-env -iA nixpkgs.pkgsStatic.lsof

      - run: /nix/var/nix/profiles/default/bin/nix-env -iA nixpkgs.pkgsStatic.gettext

      - run: /nix/var/nix/profiles/default/bin/nix-env -iA nixpkgs.pkgsStatic.m4

      - run: /nix/var/nix/profiles/default/bin/nix-env -iA nixpkgs.pkgsStatic.ncdu

      - run: /nix/var/nix/profiles/default/bin/nix-env -iA nixpkgs.pkgsStatic.wget

      - uses: mxschmitt/action-tmate@v3
        if: ${{ failure() }}
        timeout-minutes: 30
