name: Pack prebuilt

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  base:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker pull curoky/dotbox:stage-prebuilt
      - run: |
          id=$(docker create curoky/dotbox:stage-prebuilt)
          docker cp $id:/output - > output.tar
          docker rm -v $id

      - uses: actions/upload-artifact@v4
        with:
          name: output.tar
          path: output.tar
