name: pack prebuilt

on:
  push:
    paths:
      - '.github/workflows/pack-prebuilt.yaml'
      - 'prebuilt/**'
  workflow_dispatch:
  # schedule:
  #   - cron: '0 0 - name: - name: 0'

jobs:
  macos:
    runs-on: ubuntu-latest
    # runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: Homebrew/actions/setup-homebrew@master
      - uses: actions/setup-python@v5
        with:
          python-version: '3'
      # - uses: Homebrew/actions/setup-homebrew@master
      # - run: brew install coreutils
      # - run: echo "/opt/homebrew/opt/coreutils/libexec/gnubin" >> $GITHUB_PATH
      - run: |
          cd prebuilt/macos/
          ./pack.sh
          ./pack-conda.sh

      - uses: svenstaro/upload-release-action@v2
        with:
          file: prebuilt/macos/tmp/prebuilt.darwin_arm64.tar.gz
          asset_name: prebuilt.darwin_arm64.tar.gz
          tag: 'v1.0'
          overwrite: true

      - uses: svenstaro/upload-release-action@v2
        with:
          file: prebuilt/macos/tmp/conda.darwin_arm64.tar.gz
          asset_name: conda.darwin_arm64.tar.gz
          tag: 'v1.0'
          overwrite: true

      - uses: mxschmitt/action-tmate@v3
        if: ${{ failure() }}
        timeout-minutes: 30

  linux:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3'
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-24.11

      - run: |
          cd prebuilt/linux
          ./pack.sh

      - uses: svenstaro/upload-release-action@v2
        with:
          file: prebuilt/linux/tmp/prebuilt.linux_x86_64.tar.gz
          asset_name: prebuilt.linux_x86_64.tar.gz
          tag: 'v1.0'
          overwrite: true

      - uses: mxschmitt/action-tmate@v3
        if: ${{ failure() }}
        timeout-minutes: 30
