name: pack prebuilt

on:
  push:
    paths:
      - '.github/workflows/pack-prebuilt.yaml'
      - 'prebuilt/**'
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  macos:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: Homebrew/actions/setup-homebrew@master
      - uses: actions/setup-python@v5
        with:
          python-version: '3'
      - run: |
          cd prebuilt/macos/
          ./pack.sh

      - uses: svenstaro/upload-release-action@v2
        with:
          file: prebuilt/macos/tmp/prebuilt.darwin-arm64.tar.gz
          asset_name: prebuilt.darwin-arm64.tar.gz
          tag: 'v1.0'
          overwrite: true

      - uses: mxschmitt/action-tmate@v3
        if: ${{ failure() }}
        timeout-minutes: 30

  linux:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3'
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-24.11

      - run: |
          cd prebuilt/linux
          ./pack.sh

      - uses: svenstaro/upload-release-action@v2
        with:
          file: prebuilt/linux/tmp/prebuilt.linux_x86_64.tar.gz
          asset_name: prebuilt.linux-x86_64.tar.gz
          tag: 'v1.0'
          overwrite: true

      - uses: mxschmitt/action-tmate@v3
        if: ${{ failure() }}
        timeout-minutes: 30

  linux-tensorflow:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - run: |
          id=$(docker create curoky/dotbox:stage-tf2.5.0-cu11.0.3-cudnn8.1.0-gcc8-py3.7)
          docker cp $id:/output/tensorflow-2.5.0-cp37-cp37m-linux_x86_64.whl - > tensorflow-2.5.0-cu11.0.3-cudnn8.1.0-gcc8-cp37-cp37m-linux_x86_64.whl
          docker rm -v $id

      - run: |
          id=$(docker create curoky/dotbox:stage-tf2.5.0-cu11.4.0-cudnn8.1.0-gcc8-py3.7)
          docker cp $id:/output/tensorflow-2.5.0-cp37-cp37m-linux_x86_64.whl - > tensorflow-2.5.0-cu11.4.0-cudnn8.1.0-gcc8-cp37-cp37m-linux_x86_64.whl
          docker rm -v $id

      - uses: svenstaro/upload-release-action@v2
        with:
          file: tensorflow-2.5.0-cu11.0.3-cudnn8.1.0-gcc8-cp37-cp37m-linux_x86_64.whl
          asset_name: tensorflow-2.5.0-cu11.0.3-cudnn8.1.0-gcc8-cp37-cp37m-linux_x86_64.whl
          tag: 'v1.0'
          overwrite: true

      - uses: svenstaro/upload-release-action@v2
        with:
          file: tensorflow-2.5.0-cu11.4.0-cudnn8.1.0-gcc8-cp37-cp37m-linux_x86_64.whl
          asset_name: tensorflow-2.5.0-cu11.4.0-cudnn8.1.0-gcc8-cp37-cp37m-linux_x86_64.whl
          tag: 'v1.0'
          overwrite: true

      - uses: mxschmitt/action-tmate@v3
        if: ${{ failure() }}
        timeout-minutes: 30
