name: Pack prebuilt

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  base:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: docker pull curoky/dotbox:stage-prebuilt
      - run: |
          id=$(docker create curoky/dotbox:stage-prebuilt)
          docker cp $id:/output - > output.tar
          docker rm -v $id

      - name: test setup config
        run: |
          tar -xvf output.tar
          ./output/dotbox/docker/base/script/setup-userconf.sh ./output/dotbox/config

      - uses: actions/upload-artifact@v4
        if: ${{ github.event_name == 'workflow_dispatch' }}
        with:
          name: output.tar
          path: output.tar

      - uses: svenstaro/upload-release-action@v2
        with:
          file: output.tar
          asset_name: output.tar
          tag: 'v1.0.0'
          overwrite: true
