name: Pre Commit

on: [push]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.18'

      - uses: actions/setup-python@v2

      - run: ./bootstrap.sh
        env:
          SECRET: ${{ secrets.BOOTSTRAP_TOKEN }}

      - uses: pre-commit/action@v2.0.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
