name: prepack

on:
  push:
    paths:
      - '.github/workflows/prepack.yaml'
      - 'prepack/**'
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  packed-sre-tools:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        include:
          - os: linux
            arch: x86_64
          - os: darwin
            arch: arm64
    steps:
      - uses: actions/checkout@v4
      - uses: Homebrew/actions/setup-homebrew@master
      - run: brew install makeself

      - run: |
          cd prepack/packed-sre-tools/${{ matrix.os }}
          ./pack.sh

      - uses: svenstaro/upload-release-action@v2
        with:
          file: prepack/packed-sre-tools/${{ matrix.os }}/tmp/sre-tools.${{ matrix.os }}-${{ matrix.arch }}.gzip.sh
          asset_name: packed-sre-tools.${{ matrix.os }}-${{ matrix.arch }}.gzip.sh
          tag: 'v1.0'
          overwrite: true

      - uses: svenstaro/upload-release-action@v2
        with:
          file: prepack/packed-sre-tools/${{ matrix.os }}/tmp/sre-tools.${{ matrix.os }}-${{ matrix.arch }}.zstd.sh
          asset_name: packed-sre-tools.${{ matrix.os }}-${{ matrix.arch }}.zstd.sh
          tag: 'v1.0'
          overwrite: true

      - uses: mxschmitt/action-tmate@v3
        if: ${{ failure() }}
        timeout-minutes: 30

  packed-conda-envs-darwin-arm64:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: Homebrew/actions/setup-homebrew@master
      - run: brew install gnu-sed grep gnu-getopt makeself
      - name: add path
        run: |
          echo "/opt/homebrew/opt/grep/libexec/gnubin" >> $GITHUB_PATH
          echo "/opt/homebrew/opt/gnu-sed/libexec/gnubin" >> $GITHUB_PATH
          echo "/opt/homebrew/opt/gnu-getopt/bin" >> $GITHUB_PATH

      - run: |
          cd prepack/packed-conda-envs/darwin
          ./pack.sh

      - uses: svenstaro/upload-release-action@v2
        with:
          file: prepack/packed-conda-envs/darwin/tmp/conda-envs.darwin-arm64.gzip.sh
          asset_name: conda-envs.darwin-arm64.gzip.sh
          tag: 'v1.0'
          overwrite: true

      - uses: svenstaro/upload-release-action@v2
        with:
          file: prepack/packed-conda-envs/darwin/tmp/conda-envs.darwin-arm64.zstd.sh
          asset_name: conda-envs.darwin-arm64.zstd.sh
          tag: 'v1.0'
          overwrite: true

      - uses: mxschmitt/action-tmate@v3
        if: ${{ failure() }}
        timeout-minutes: 30

  packed-conda-envs-linux-x86_64:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: Homebrew/actions/setup-homebrew@master
      - run: brew install makeself

      - run: |
          cd prepack/packed-conda-envs/linux/
          ./pack.sh

      - uses: svenstaro/upload-release-action@v2
        with:
          file: prepack/packed-conda-envs/linux/tmp/conda-envs.linux-x86_64.gzip.sh
          asset_name: conda-envs.linux-x86_64.gzip.sh
          tag: 'v1.0'
          overwrite: true

      - uses: svenstaro/upload-release-action@v2
        with:
          file: prepack/packed-conda-envs/linux/tmp/conda-envs.linux-x86_64.zstd.sh
          asset_name: conda-envs.linux-x86_64.zstd.sh
          tag: 'v1.0'
          overwrite: true

  packed-docker-installer:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: Homebrew/actions/setup-homebrew@master
      - run: brew install makeself

      - run: |
          cd prepack/packed-docker-installer/debian10
          ./pack.sh

      - uses: svenstaro/upload-release-action@v2
        with:
          file: prepack/packed-docker-installer/debian10/tmp/docker_installer.debian10.gzip.sh
          asset_name: docker_installer.debian10.gzip.sh
          tag: 'v1.0'
          overwrite: true

      - uses: svenstaro/upload-release-action@v2
        with:
          file: prepack/packed-docker-installer/debian10/tmp/docker_installer.debian10.zstd.sh
          asset_name: docker_installer.debian10.zstd.sh
          tag: 'v1.0'
          overwrite: true

      - uses: mxschmitt/action-tmate@v3
        if: ${{ failure() }}
        timeout-minutes: 30

  packed-dotbox:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: Homebrew/actions/setup-homebrew@master
      - run: brew install makeself

      - run: |
          cd prepack/packed-dotbox/
          ./pack.sh

      - uses: svenstaro/upload-release-action@v2
        with:
          file: prepack/packed-dotbox/tmp/dotbox_installer.gzip.sh
          asset_name: dotbox_installer.gzip.sh
          tag: 'v1.0'
          overwrite: true

      - uses: mxschmitt/action-tmate@v3
        if: ${{ failure() }}
        timeout-minutes: 30

  linux-tensorflow:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - run: |
          id=$(docker create curoky/dotbox:stage-tf2.5.0-cu11.0.3-cudnn8.1.0-gcc8-py3.7)
          docker cp $id:/output/tensorflow-2.5.0-cp37-cp37m-linux_x86_64.whl - > tensorflow-2.5.0-cu11.0.3-cudnn8.1.0-gcc8-cp37-cp37m-linux_x86_64.whl
          docker rm -v $id

      - run: |
          id=$(docker create curoky/dotbox:stage-tf2.5.0-cu11.4.0-cudnn8.1.0-gcc8-py3.7)
          docker cp $id:/output/tensorflow-2.5.0-cp37-cp37m-linux_x86_64.whl - > tensorflow-2.5.0-cu11.4.0-cudnn8.1.0-gcc8-cp37-cp37m-linux_x86_64.whl
          docker rm -v $id

      - uses: svenstaro/upload-release-action@v2
        with:
          file: tensorflow-2.5.0-cu11.0.3-cudnn8.1.0-gcc8-cp37-cp37m-linux_x86_64.whl
          asset_name: tensorflow-2.5.0-cu11.0.3-cudnn8.1.0-gcc8-cp37-cp37m-linux_x86_64.whl
          tag: 'v1.0'
          overwrite: true

      - uses: svenstaro/upload-release-action@v2
        with:
          file: tensorflow-2.5.0-cu11.4.0-cudnn8.1.0-gcc8-cp37-cp37m-linux_x86_64.whl
          asset_name: tensorflow-2.5.0-cu11.4.0-cudnn8.1.0-gcc8-cp37-cp37m-linux_x86_64.whl
          tag: 'v1.0'
          overwrite: true

      - uses: mxschmitt/action-tmate@v3
        if: ${{ failure() }}
        timeout-minutes: 30
